# Generated by Django 5.2.9 on 2026-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='What does this do for the body?'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Nairobi Warehouse', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, help_text='Dosage instructions (e.g., 1 tablet daily)'),
        ),
    ]
