# Generated by Django 5.2.9 on 2026-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_benefits_product_location_product_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter each benefit on a new line'),
        ),
    ]
